name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    name: Backend (format check -> lint -> build -> test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install
        run: npm ci
      - name: Format Check
        run: npm run format:check:backend
      - name: Lint
        run: npm run lint:backend
      - name: Build
        run: npm run build:backend
      - name: Test
        run: npm run test:backend

  frontend:
    name: Frontend (format check -> lint -> build -> test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm
      - name: Install
        run: npm ci
      - name: Format Check
        run: npm run format:check:frontend
      - name: Lint
        run: npm run lint:frontend
      - name: Build
        run: npm run build:frontend
      - name: Test
        run: npm run test:frontend
